language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

sudo: false

install:
  - python setup.py install

script:
  - python tests/test.py -l javascript tests/stuff.js
  - python tests/test.py -l python tests/stuff.py
