language: python
python:
  - "3.8"
  - "3.9"

sudo: false

install:
  - python -m pip install -r requirements.txt
  - python setup.py install

script:
  - python tests/test.py -l javascript tests/stuff.js
  - python tests/test.py -l python tests/stuff.py
