language: python
python:
  - "3.8"
  - "3.9"

dist: "bionic"
os: "linux"

cache:
  directories:
    - $HOME/.cache/wsyntree

install:
  - python -m pip install requests coloredlogs pygit2
  - python -m pip install -r requirements.txt
  - python setup.py install

script:
  - wsyntree-collector file -l javascript tests/stuff.js
  - wsyntree-collector file -l python tests/stuff.py
  - wsyntree-collector file -l ruby tests/stuff.rb
  - wsyntree-collector file -l c tests/stuff.c
  - wsyntree-collector file -l cpp tests/stuff.cpp
  - wsyntree-collector file -l java tests/stuff.java
  - wsyntree-collector file -l rust tests/stuff.rs
  - wsyntree-collector file -l go tests/stuff.go
