
version: '3'

services:
#  wst-test:
#    build:
#      context: .
#      dockerfile: docker/testing.dockerfile
#    depends_on:
#      - neo4j
#    restart: "no"
#    command: "wait-for-it neo4j:7687 -- /wst/docker/test-collector.sh"
#    environment:
#      - NEO4J_BOLT_URL=bolt://neo4j:pass@neo4j:7687

  neo4j:
    image: neo4j:4.4
    ports:
      - 127.0.0.1:9784:7474
      - 127.0.0.1:9787:7687
    environment:
      - NEO4J_AUTH=none
    # volumes:
    #   - wst_neo4j_data:/data
